# Default values for myhelmchartplanet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1
 
image:
    repository: mydeveloperplanet/mykubernetesplanet
    tag: 0.0.2-SNAPSHOT
    pullPolicy: IfNotPresent
 
nameOverride: ""
fullnameOverride: ""
 
service:
    type: NodePort
    port: 8080
    nodePort: 30036
 
ingress:
    enabled: false
    annotations: {}
    path: /
    hosts:
        - chart-example.local
    tls: []
 
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
